import { FunctionComponent, ReactNode } from 'react'
import Head from 'next/head'
import { Navbar } from '../Navbar'
import styles from './MainLayout.module.css'


interface MainLayoutProps {
  children?: ReactNode
}

const MainLayout: FunctionComponent<MainLayoutProps> = ({ children }) => {
  return (
    <>
      <Head>
        <title>Contact Santiago</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initia l-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Navbar />
      <main className={`${styles.main} `}>
        {children}
      </main>
    </>
  )
}

export default MainLayout